# Generated by Django 3.2.1 on 2021-06-09 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='latitude',
            field=models.DecimalField(decimal_places=8, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='longitude',
            field=models.DecimalField(decimal_places=8, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='resultado',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
    ]
